name: Auto-update offers

on:
  schedule:
    - cron: '0/10 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: node update
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatic offers update
